# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: s4u/maven-settings-action@v3.0.0
      with:
        sonatypeSnapshots: true
        githubServer: false
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - uses: actions/checkout@v4
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: sonatype-nexus-snapshots
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    #- name: Publish package
    #  run: mvn --batch-mode deploy
    #  env:
    #    MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
    #    MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}    
    #- name: Build with Maven
    #  run: mvn -B verify --file pom.xml
    - uses: s4u/maven-settings-action@v3.0.0
      with:
        sonatypeSnapshots: true
        githubServer: false
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY1 }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG
    - id: publish-to-central
      name: Publish to Central Repository
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      run: |
        mvn \
        --no-transfer-progress \
        --batch-mode \
        -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
        clean verify deploy    

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
